# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mparticle-ios-integration-singular' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mparticle-ios-integration-singular
  pod 'mParticle-Apple-SDK/mParticle', '~> 8.0-beta'
  pod 'Singular-SDK'
end

target 'mparticle_ios_integration_singularTests' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for mparticle-ios-integration-singular
    pod 'mParticle-Apple-SDK/mParticle', '~> 8.0-beta'
    pod 'Singular-SDK'
end
